---
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://portal-mysql/portal?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: portal
      password: site@p#ortal
      filters: log4j,wall,mergeStat
      sql-script-encoding: UTF-8
      schema: classpath*:sql/*-schema.sql
      data: classpath*:sql/*-data.sql
      initialize: false

logging:
  level: warn 
  config: config/logback-spring.xml

io:
  file-host: http://localhost/attachments
  file-upload-path: /attachments 
